services:
  - type: web
    name: pdf-metadata-cleaner
    env: node
    buildCommand: npm install
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production 